export const httpFlags = {
  FORBIDDEN: 'FORBIDDEN',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_BODY: 'INVALID_BODY',
  INVALID_PARAM: 'INVALID_PARAM',
  INVALID_HEADERS: 'INVALID_HEADERS',
  INVALID_URL: 'INVALID_URL'
}
