image: node:latest

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay
  DOCKER_TLS_CERTDIR: ''

services:
  - docker:18.09-dind

before_script:
  - docker info

include:
  - local: '.gitlab/ci/build-stage.gitlab-ci.yml'
  - local: '.gitlab/ci/test-stage.gitlab-ci.yml'
