image: docker:18.09

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: '/certs'

services:
  - docker:18.09-dind

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add curl jq python3 python3-dev build-base libffi-dev libressl-dev gettext
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - pip install docker-compose

include:
  - local: '.gitlab/ci/build-stage.gitlab-ci.yml'
  - local: '.gitlab/ci/test-stage.gitlab-ci.yml'
