image: node:latest

stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

before_script:
  - docker info
  - apk update
  - apk upgrade
  - apk add python python-dev py-pip build-base
  - pip install docker-compose
  - git config --global user.name "${GITLAB_USER_NAME}"
  - git config --global user.email "${GITLAB_USER_EMAIL}"
  - export APP_NAME=$(node -e "console.log(require('./package.json').name)")
  - export APP_VERSION=$(node -e "console.log(require('./package.json').version)")

services:
  - name: docker:dind

include:
  - local: '.gitlab/ci/build-stage.gitlab-ci.yml'
  - local: '.gitlab/ci/test-stage.gitlab-ci.yml'
