build and test:
  stage: build and test
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - cp .env.example .env
    - docker-compose -f docker-compose.yml run app npm run test
