cache:
  paths:
    - node_modules/

prepare:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
