staging:
  type: deploy
  stage: deploy-staging
  image: ruby:latest
  before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
  variables:
    APP_ENV: 'staging'
    CLOUDINARY_CLOUD_NAME: '${CLOUDINARY_CLOUD_NAME}'
    CLOUDINARY_API_KEY: '${CLOUDINARY_API_KEY}'
    CLOUDINARY_API_SECRET: '${CLOUDINARY_API_SECRET}'
    CLOUDINARY_ASSETS: '${CLOUDINARY_ASSETS}'
    JWT_SECRET: '${JWT_SECRET}'
    ENCRYPT_JWT_SECRET: '${ENCRYPT_JWT_SECRET}'
    JWT_EXPIRATION: '${JWT_EXPIRATION}'
    MONGO_DB_URI: '${MONGO_DB_URI_STAGING}'
    MONGO_DB_DB_NAME: '${MONGO_DB_DB_NAME}'
    MONGO_DB_USER: '${MONGO_DB_USER_STAGING}'
    MONGO_DB_PASS: '${MONGO_DB_PASS_STAGING}'
    MONGO_DB_AUTH_SOURCE: '${MONGO_DB_AUTH_SOURCE}'
  script:
    - dpl --provider=heroku --app="${HEROKU_APP_STAGING}" --api-key="${HEROKU_API_KEY_STAGING}"
  rules:
    - if: '$CI_COMMIT_BRANCH == "develop"'
      when: on_success
