testing:
  stage: test
  needs:
    - job: install_dependencies
      artifacts: true
  artifacts:
    paths:
      - node_modules
      - dist
      - package.json
      - package-lock.json
      - coverage
      - junit.xml
    reports:
      junit:
        - junit.xml
        - coverage/*.xml
    expire_in: 7d
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - cp .env.example .env
    - npm run dependency:local
    - sleep 5
    - npm run test
