test:integration:
  stage: test
  needs:
    - job: prepare
      artifacts: true
  artifacts:
    paths:
      - node_modules
      - dist
      - package.json
      - package-lock.json
      - coverage
      - junit.xml
    reports:
      junit:
        - junit.xml
        - coverage/*.xml
    expire_in: 7d
  retry:
    max: 2
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
  script:
    - cp .env.example .env
    - npm install
    - npm run dependency:local
    - sleep 5
    - docker-compose -f docker-compose.yml run
      -e APP_ENV="test"
      -e CLOUDINARY_CLOUD_NAME="${CLOUDINARY_CLOUD_NAME}"
      -e CLOUDINARY_API_KEY="${CLOUDINARY_API_KEY}"
      -e CLOUDINARY_API_SECRET="${CLOUDINARY_API_SECRET}"
      -e CLOUDINARY_ASSETS="${CLOUDINARY_ASSETS}"
      -e JWT_SECRET="${JWT_SECRET}"
      -e ENCRYPT_JWT_SECRET="${ENCRYPT_JWT_SECRET}"
      -e JWT_EXPIRATION="${JWT_EXPIRATION}"
      app npm run test
